### ISSUE TITLE
Crash Tapeutape @ startup

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/PlagiatSetup#1]
Hack 1 : Changer l'ordre des morceaux dans Tapeutape pour que par défaut il charge le bon.
Hack 2 : fixer le bug de Tapeutape qui le crash quand il reçoit un control change qu'il ne peut exécuter

**Comment by jean-emmanuel** [comment]
Hack 3: faire comme si ça n'arrivait pas

**Comment by jean-emmanuel** [comment]
feel free to reopen ofcourssssse
